ads/urls.py
from django.urls import path
from ads.views import (AdsCreateView, AdsListView,
                       AdsDetailView, AdsDeleteView, AdsUpdateView, AdsTableView, make_hot, up_ad, AdsUncheckedListView,
                       change_status)

urlpatterns = [
    path('ads_list/', AdsListView.as_view(), name='ads_list'),
    path('ads_unchecked/', AdsUncheckedListView.as_view(), name='ads_unchecked'),
    path('ads_table/', AdsTableView.as_view(), name='ads_table'),
    path('ads_create/', AdsCreateView.as_view(), name='ads_create'),
    path('ads_detail/<int:pk>/', AdsDetailView.as_view(), name='ads_detail'),
    path('ads_delete/<int:pk>/', AdsDeleteView.as_view(), name='ads_delete'),
    path('ads_update/<int:pk>/', AdsUpdateView.as_view(), name='ads_update'),
    path('make_hot/<int:pk>/', make_hot, name='make_hot'),
    path('up_ad/<int:pk>/', up_ad, name='up_ad'),
    path('change_status/<int:pk>/', change_status, name='change_status'),
]

kelechek_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from kelechek_project import settings

urlpatterns = [
    path('upr/admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('api/kelechek/', include('api.urls')),
    path('api/kelechek/rest-auth/', include('dj_rest_auth.urls')),
    path('', include('pages.urls')),
    path('', include('news.urls')),
    path('', include('faq.urls')),
    path('', include('ads.urls')),
    path('votes/', include('quotes.urls')),
    path('protocols/', include('protocols.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATICFILES_DIRS)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.error_404_view'

agreement/models.py
from django.db import models


BOOKKEEPER_CHOICE = [
    ('Первоначальный взнос', 'Первоначальный взнос'),
    ('Пополнение', 'Пополнение'),
    ('Вступительный взнос', 'Вступительный взнос'),
    ('Погашение ссуды', 'Погашение ссуды'),
]


class UserAgreement(models.Model):
    agreement_city = models.CharField('Город договора', max_length=255,
                                      help_text='пример: г. Бишкек',
                                      null=True, blank=True)
    agreement_by_whom = models.TextField('В лице от кооператива',
                                         null=True, blank=True)
    agreement_date = models.DateField('Дата Договора об участии',
                                      null=True, blank=True)
    agreement_document_number = models.IntegerField('№ Договора об участии',
                                                    null=True, blank=True)
    agreement_amount = models.CharField('ссуда на сумму', max_length=255,
                                        help_text="787 500",
                                        null=True, blank=True)
    agreement_amount_text = models.CharField('ссуда на сумму в виде текста',
                                             null=True, blank=True,
                                             help_text="Семьсот восемьдесят семь тысяч пятьсот",
                                             max_length=255)
    agreement_month = models.IntegerField('Месяцев на ссуду',
                                          help_text='120', default=0,
                                          null=True, blank=True)
    agreement_month_text = models.CharField('Месяцев на ссуду в виде текста',
                                            help_text='сто двадцать',
                                            max_length=255,
                                            null=True, blank=True)
    agreement_home = models.TextField('Залоговое имущество',
                                      null=True, blank=True,
                                      help_text='''Квартира, полезной площадью 34,1 кв.м., 
                                    жилой площадью 18,2 кв.м., находящийся по адресу''')
    agreement_purchase = models.CharField('Договор купли-продажи №',
                                          max_length=255,
                                          null=True, blank=True)
    agreement_purchase_date = models.DateField('Дата Договора купли-продажи',
                                               null=True, blank=True)
    agreement_chairman = models.CharField(verbose_name='В лице Председателя',
                                          max_length=255, null=True,
                                          blank=True,
                                          help_text='в лице Председателя Правления Курманалиева Эламана Курманалиевича')
    agreement_chairman2 = models.CharField(verbose_name='В лице Председателя',
                                           max_length=255, null=True,
                                           blank=True,
                                           help_text='''в лице Председателя Правления 
                                    Курманалиева Эламана Курманалиевича''')
    home_price = models.IntegerField(default=0,
                                     verbose_name='Желаемая стоимость',
                                     help_text='Желаемая стоимость недвижимого имущества')
    home_month_price = models.IntegerField(default=0,
                                           help_text='Член кооператива оплачивает сумму в размере',
                                           verbose_name='Оплачиваемся сумма')
    home_price_text = models.CharField(max_length=255,
                                       verbose_name='Желаемая стоимость в письменном виде',
                                       help_text='''Желаемая стоимость недвижимого 
                                    имущества в письменном виде (два миллиона сомов)''')
    home_price_25percent_text = models.CharField(max_length=255,
                                                 verbose_name='25% от общей суммы в письменном виде',
                                                 help_text='25% от общей суммы в письменном виде')
    home_price_4percent_text = models.CharField(max_length=255,
                                                verbose_name='4% от общей суммы в письменном виде',
                                                help_text='4% от общей суммы в письменном виде')
    loan_amount_text = models.CharField('Оплачиваемая сумма в письменном виде',
                                        max_length=255, null=True, blank=True)
    prilojenie_date = models.DateField('Дата приложения',
                                       null=True, blank=True)
    prilojenie_count = models.IntegerField('Количество месяцев', default=0,
                                           null=True, blank=True)
    prilojenie_count_text = models.CharField('Количество месяцев текст',
                                             max_length=255, null=True,
                                             blank=True,
                                             help_text='''Текст количество 
                                             месяцев (6 месяцев)''')
    anketa_date_register = models.DateField('Дата регистрации анкеты',
                                            null=True, blank=True)
    contract_date = models.DateField('Дата договора ссуды',
                                     null=True, blank=True)
    contract_city = models.CharField('Город договора ссуды',
                                     help_text='г. Бишкек',
                                     max_length=255, null=True, blank=True)
    deposit_date = models.DateField('Дата договора о залоге',
                                    null=True, blank=True)
    deposit_date_text = models.CharField(
        'Дата договора о залоге в письменном виде',
        max_length=255, null=True, blank=True,
        help_text="""
                                         Двадцатое сентрября две тысячри двадцать второго года""")
    application_date = models.DateField('Дата приложения',
                                        null=True, blank=True)
    law_district = models.CharField('Регион нотариуса',
                                    max_length=255, null=True, blank=True)
    bookkeeper_choice = models.CharField(max_length=255,
                                         choices=BOOKKEEPER_CHOICE, null=True,
                                         blank=True,
                                         default='Первоначальный взнос',
                                         verbose_name="Выбор взноса")
    deposite_by = models.CharField(max_length=255, null=True, blank=True,
                                   verbose_name="По дов")
    law_payment = models.IntegerField('юридическое сопровождение', default=0,
                                      null=True, blank=True)
    law_payment_text = models.CharField('юридическое сопровождение текст',
                                        max_length=255, null=True, blank=True)
    percent_25_field = models.IntegerField("25%", null=True, blank=True,
                                           default=25)
    percent_25_field_text = models.CharField(
        '25% в виде текст (двадцвать пять процентов)',
        max_length=255, null=True, blank=True)
    percent_4_field = models.IntegerField("4%", null=True, blank=True,
                                          default=4)
    percent_4_field_text = models.CharField(
        '4%  в виде текст (четыре процента)',
        max_length=255, null=True, blank=True)

    def __str__(self):
        return f'{self.id}'

    def percent_25(self):
        percent = self.percent_25_field / 100
        return int(self.home_price * percent)

    def percent_4(self):
        percent = self.percent_4_field / 100
        return int(self.home_price * percent)

agreement/views.py
from django.shortcuts import render

# Create your views here.

templates/agreement/agreement1_update.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}
{% block title %}Создать договор | {% endblock %}
{% block content %}
<!-- Start breadcumb Area -->
<div class="page-area">
    <div class="breadcumb-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="breadcrumb">
                    <div class="bread-inner">
                        <div class="section-headline white-headline">
                            <h2>Создать договор</h2>
                        </div>
                        <ul class="breadcrumb-bg">
                            <li class="home-bread"><a href="{% url 'home' %}">Главная</a></li>
                            <li>Создать договор</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcumb Area -->

<div class="container p-tb-2">

    <form id="post_form" method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-md-6">
            <div id="div_id_agreement_date" class="form-group">
                <label for="id_agreement_date" class="">
                    Дата Договора об участии
                </label>


                <div class="">
                    <input type="date" value="{{object.agreement_date|date:'Y-m-d' }}" name="agreement_date"
                        class="form-control dateinput" required="" id="id_agreement_date">
                </div>
            </div>
            {{ form.agreement_document_number|as_crispy_field }}
            {{form.home_price|as_crispy_field }}
            {{form.home_price_text|as_crispy_field }}
            {{form.law_payment|as_crispy_field }}
            {{form.law_payment_text|as_crispy_field }}
            {{form.percent_25_field|as_crispy_field }}
            {{form.percent_25_field_text|as_crispy_field }}
            {{form.home_price_25percent_text|as_crispy_field }}
        </div>
        <div class="col-md-6">
            {{ form.agreement_city|as_crispy_field }}
            {{form.agreement_chairman|as_crispy_field }}
            {{form.home_month_price|as_crispy_field }}
            {{form.loan_amount_text|as_crispy_field }}

            {{form.percent_4_field|as_crispy_field }}
            {{form.percent_4_field_text|as_crispy_field }}
            {{form.home_price_4percent_text|as_crispy_field }}

            <input style="margin-top: 25px" class="btn btn-success" type="submit" name="submit" value="Изменить">
        </div>
    </form>
</div>
{% endblock %}

templates/agreement/agreement2_update.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}
{% block title %}Создать договор | {% endblock %}
{% block content %}
<!-- Start breadcumb Area -->
<div class="page-area">
    <div class="breadcumb-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="breadcrumb">
                    <div class="bread-inner">
                        <div class="section-headline white-headline">
                            <h2>Создать договор</h2>
                        </div>
                        <ul class="breadcrumb-bg">
                            <li class="home-bread"><a href="{% url 'home' %}">Главная</a></li>
                            <li>Создать договор</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcumb Area -->


<div class="container p-tb-2">
    <form id="post_form" method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-md-6">
            {% csrf_token %}
            <div id="div_id_contract_date" class="form-group">
                <label for="id_contract_date" class="">
                    Дата договора ссуды
                </label>

                <div class="">
                    <input type="date" value="{{object.contract_date|date:'Y-m-d' }}" name="contract_date"
                        class="dateinput form-control" id="id_contract_date">
                </div>

            </div>
            {{ form.agreement_amount|as_crispy_field }}
            {{ form.agreement_amount_text|as_crispy_field }}
            {{ form.agreement_month|as_crispy_field }}
            {{ form.agreement_month_text|as_crispy_field }}
            <input style="margin-top: 25px" class="btn btn-success" type="submit" name="submit" value="Изменить">
        </div>
        <div class="col-md-6">
            {{ form.contract_city|as_crispy_field }}
            {{ form.agreement_chairman2|as_crispy_field }}
            {{ form.agreement_home|as_crispy_field }}
        </div>
    </form>
</div>
{% endblock %}

templates/agreement/agreement3.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Приложение к договору об участии| Келечек - Жилищный кооператив Кыргызстан, Бишкек</title>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords"
        content="Жилищный кооператив, доступное жилье в Бишкеке, Келечек кооператив, Жилищный кооператив Келечек, Жилищный кооператив, Жилищный кооператив Бишкек, Жилищный кооператив Кыргызстан, Недвижимость, Недвижимость в рассрочку, Альтернатива ипотеке, Жилье в аренду в Бишкеке">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google-site-verification" content="c_11ijAMXTEgBWYztyw9vgf31T3ktXLRsKKTdCzmzJY" />
    <!-- favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo/favicon.png' %}">
</head>

<body>
    <style>
        p {
            margin: 0;
        }

        .padding-bottom {
            padding-bottom: 10px;
        }

        td {
            padding: 10px;
        }

        .text-center {
            text-align: center;
        }
    </style>

    <p class="padding-bottom">Приложение №1 к договору ссуды от {{object.user_agreement.contract_date}}</p>
    <p class="padding-bottom">
        <strong>Сумма ссуды</strong>
        –
        <strong>
            {{object.user_agreement.agreement_amount}} ({{object.user_agreement.agreement_amount_text}}) сом 00 тыйын
        </strong>
        .
    </p>
    <p class="padding-bottom">
        <strong>Срок ссуды</strong>
        {{object.user_agreement.agreement_month}} ({{object.user_agreement.agreement_month_text}}) месяцев.
    </p>
    <table border="1" cellspacing="0" cellpadding="0">
        <tbody>
            <tr class="text-center">
                <td width="140" nowrap="" colspan="2" valign="bottom">
                    <p>Дата погашения</p>
                </td>
                <td width="93" nowrap="" valign="bottom">
                    <p>Платежи</p>
                </td>
                <td width="72" nowrap="" colspan="2" valign="bottom">
                    <p>Итого</p>
                </td>
                <td width="120" colspan="2" valign="bottom">
                    <p>Остаток основной суммы</p>
                </td>
            </tr>

            {% for i, x in application_info %}
            <tr>
                <td colspan="2">15 {{i}}</td>
                <td>{{result}}</td>
                <td colspan="2">
                    {% if total < x %}
                        {{total}}
                    {% else %}
                        {{ x }}
                    {% endif %}
                </td>
                <td colspan="2">{{x}}</td>
            </tr>
            {% endfor %}
            {% if last_summ == result %}
            <tr>
                <td colspan="2">15 {{last_month|date:'F Y'|lower}}</td>
                <td>{{ last_summ }}</td>
                <td colspan="2">{{total}}</td>
                <td colspan="2">0</td>
            </tr>
            {% endif %}


            <tr>
                <td colspan="4" width="341" valign="top">
                    <p style="width: 300px">
                        {% if object.user_region.region_title %}
                            {% autoescape off %}
                                {{object.user_region.region_title}}
                            {% endautoescape %}
                        {% else %}
                            Некоммерческий жилищно-накопительный кооператив взаимопомощи  «Один Шаг к Будущему»
                        {% endif %}
                    </p>
                    <p>
                        {% if object.user_region.region_address %}
                            {% autoescape off %}
                                {{object.user_region.region_address}}
                            {% endautoescape %}
                        {% else %}
                            Юридический адрес. Бишкек, <br>ул.Севастопольская д. 12
                        {% endif %}
                    </p>
                    <p>
                        ИНН:
                        {% if object.user_region.region_inn %}
                            {{object.user_region.region_inn}}
                        {% else %}
                            01510201910197
                        {% endif %}
                    </p>
                    <p>
                        ОКПО:
                        {% if object.user_region.region_okpo %}
                            {{object.user_region.region_okpo}}
                        {% else %}
                            30417660
                        {% endif %}
                    </p>

                    <p>
                        Номер тел: {% if object.user_region.region_phone %}
                        {{object.user_region.region_phone}} {% else %} +996 702 250538 {% endif %}
                    </p>
                    <p>
                        {% if object.user_agreement.agreement_chairman %}
                            {{object.user_agreement.agreement_chairman}}
                        {% else %}
                            {% if object.user_region.region_director %}
                                {{object.user_region.region_director}}
                            {% else %}
                                зам.председатель правление Кооператива Кенжегулов Б.А
                            {% endif %}
                        {% endif %}
                    </p>
                    <br>
                    <p>
                        Подпись и Печать
                    </p>
                    <p>___________________ </p>
                </td>
                <td colspan="4" width="341" valign="top"
                    style="margin-left: 15px;">
                    <p>
                        Член Кооператива
                    </p>
                    <p>
                        <b> {{ object.user_full_name }} </b>
                    </p>
                    <p>
                        Место проживания: <b> {{ object.user_passport_address }} </b>
                    </p>
                    <p>
                        Паспорт серии <b> {{ object.username.upper }} </b>
                    </p>
                    <p>
                        от <b> {{ object.user_passport_from_date }} </b>
                    </p>
                    <p>
                        Выдан <b> {{ object.user_passport_given_by }} </b>
                    </p>
                    <p>
                        ИНН:<b> {{ object.user_inn }} </b>
                    </p>
                    <p>
                        Контактный
                    </p>
                    <p>
                        Телефон 1: <b> {{ object.user_phone_number1 }} </b>
                    </p>
                    {% if object.user_phone_number2 %}
                        <p>
                            Телефон 2: <b> {{ object.user_phone_number2 }} </b>
                        </p>
                    {% endif %}
                    <br>
                    <br>
                    <p>
                        Подпись
                    </p>

                    <p>
                        <b> {{ last_name }} </b> __________
                    </p>
                </td>
            </tr>

        </tbody>
    </table>
</body>

</html>

templates/agreement/agreement3_update.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}
{% block title %}Создать договор | {% endblock %}
{% block content %}
<!-- Start breadcumb Area -->
<div class="page-area">
    <div class="breadcumb-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="breadcrumb">
                    <div class="bread-inner">
                        <div class="section-headline white-headline">
                            <h2>Создать договор</h2>
                        </div>
                        <ul class="breadcrumb-bg">
                            <li class="home-bread"><a href="{% url 'home' %}">Главная</a></li>
                            <li>Создать договор</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcumb Area -->


<div class="container p-tb-2">
    <div class="col-md-6">
        <form id="post_form" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div id="div_id_application_date" class="form-group">
                <label for="id_application_date" class="">
                    Дата приложения
                </label>

                <div class="">
                    <input type="date" name="application_date" value="{{object.application_date|date:'Y-m-d' }}"
                           class="dateinput form-control" id="id_application_date">
                </div>
            </div>
            {{ form.agreement_amount|as_crispy_field }}
            {{ form.agreement_month|as_crispy_field }}

            <input type="submit" name="submit" value="Создать">
        </form>
    </div>
</div>
{% endblock %}

templates/agreement/agreement4_update.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}
{% block title %}Создать договор | {% endblock %}
{% block content %}
<!-- Start breadcumb Area -->
<div class="page-area">
    <div class="breadcumb-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="breadcrumb">
                    <div class="bread-inner">
                        <div class="section-headline white-headline">
                            <h2>Создать договор</h2>
                        </div>
                        <ul class="breadcrumb-bg">
                            <li class="home-bread"><a href="{% url 'home' %}">Главная</a></li>
                            <li>Создать договор</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcumb Area -->


<div class="container p-tb-2">
    <div class="col-md-12">
        <form id="post_form" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-md-6">
                {{ form.agreement_city|as_crispy_field }}
                <div id="div_id_deposit_date" class="form-group">
                    <label for="id_deposit_date" class="">
                        Дата договора о залоге
                    </label>
                    <div class="">
                        <input type="date" name="deposit_date" value="{{ object.deposit_date|date:'Y-m-d' }}"
                            class="dateinput form-control" id="id_deposit_date">
                    </div>
                </div>
                {{ form.deposit_date_text|as_crispy_field }}
                {{ form.agreement_by_whom|as_crispy_field }}
                {{ form.agreement_amount|as_crispy_field }}
                {{ form.agreement_amount_text|as_crispy_field }}
            </div>
            <div class="col-md-6">
                {{ form.agreement_month|as_crispy_field }}
                {{ form.agreement_month_text|as_crispy_field }}
                {{ form.agreement_home|as_crispy_field }}
                {{ form.law_district|as_crispy_field }}
                {{ form.deposite_by|as_crispy_field }}

                <input style="margin-top: 25px" class="btn btn-success" type="submit" name="submit" value="Изменить">
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/agreement/agreement_1_update.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}
{% block title %}Создать договор | {% endblock %}
{% block content %}
<!-- Start breadcumb Area -->
<div class="page-area">
    <div class="breadcumb-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="breadcrumb">
                    <div class="bread-inner">
                        <div class="section-headline white-headline">
                            <h2>Создать договор</h2>
                        </div>
                        <ul class="breadcrumb-bg">
                            <li class="home-bread"><a href="{% url 'home' %}">Главная</a></li>
                            <li>Создать договор</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcumb Area -->

<div class="container p-tb-2">

    <form id="post_form" method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-md-6">
            <div id="div_id_prilojenie_date" class="form-group">
                <label for="id_prilojenie_date" class="">
                    Дата Договора об участии
                </label>


                <div class="">
                    <input type="date" value="{{object.prilojenie_date|date:'Y-m-d' }}" name="prilojenie_date"
                        class="form-control dateinput" required="" id="id_prilojenie_date">
                </div>
            </div>

            {{form.prilojenie_count|as_crispy_field}}
            {{form.prilojenie_count_text|as_crispy_field}}
        </div>
        <div class="col-md-6">

            <input style="margin-top: 25px" class="btn btn-success" type="submit" name="submit" value="Изменить">
        </div>
    </form>
</div>
{% endblock %}

templates/agreement/agreement_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Создать договор | {% endblock %}
{% block content %}
    <!-- Start breadcumb Area -->
    <div class="page-area">
        <div class="breadcumb-overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="breadcrumb">
                        <div class="bread-inner">
                            <div class="section-headline white-headline">
                                <h2>Создать договор</h2>
                            </div>
                            <ul class="breadcrumb-bg">
                                <li class="home-bread"><a href="{% url 'home' %}">Главная</a></li>
                                <li>Создать договор</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End breadcumb Area -->


    <div class="container p-tb-2">
        <div class="col-md-6">
            <form id="post_form" method="post" action="" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" name="submit" value="Создать">
            </form>
        </div>
    </div>
{% endblock %}