ads/urls.py
from django.urls import path
from ads.views import (AdsCreateView, AdsListView,
                       AdsDetailView, AdsDeleteView, AdsUpdateView, AdsTableView, make_hot, up_ad, AdsUncheckedListView,
                       change_status)

urlpatterns = [
    path('ads_list/', AdsListView.as_view(), name='ads_list'),
    path('ads_unchecked/', AdsUncheckedListView.as_view(), name='ads_unchecked'),
    path('ads_table/', AdsTableView.as_view(), name='ads_table'),
    path('ads_create/', AdsCreateView.as_view(), name='ads_create'),
    path('ads_detail/<int:pk>/', AdsDetailView.as_view(), name='ads_detail'),
    path('ads_delete/<int:pk>/', AdsDeleteView.as_view(), name='ads_delete'),
    path('ads_update/<int:pk>/', AdsUpdateView.as_view(), name='ads_update'),
    path('make_hot/<int:pk>/', make_hot, name='make_hot'),
    path('up_ad/<int:pk>/', up_ad, name='up_ad'),
    path('change_status/<int:pk>/', change_status, name='change_status'),
]

kelechek_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from kelechek_project import settings

urlpatterns = [
    path('upr/admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('api/kelechek/', include('api.urls')),
    path('api/kelechek/rest-auth/', include('dj_rest_auth.urls')),
    path('', include('pages.urls')),
    path('', include('news.urls')),
    path('', include('faq.urls')),
    path('', include('ads.urls')),
    path('votes/', include('quotes.urls')),
    path('protocols/', include('protocols.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATICFILES_DIRS)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.error_404_view'

protocols/urls.py
from django.urls import path

from protocols.views import (ProtocolUpdateView, ProtocolDetailView,
                             ProtocolCreateView, ProtocolListView)

urlpatterns = [
    path('protocol-update/<int:pk>/', ProtocolUpdateView.as_view(), name='protocol_update'),
    path('protocol-detail/<int:pk>/', ProtocolDetailView.as_view(), name='protocol_detail'),
    path('protocol-create/', ProtocolCreateView.as_view(), name='protocol_create'),
    path('protocol-list/', ProtocolListView.as_view(), name='protocol_list'),
]

protocols/models.py
from django.db import models

from users.models import CustomUser


class UserProtocol(models.Model):
    protocol_created_user = models.ForeignKey(CustomUser,
                                              related_name='user_protocol',
                                              on_delete=models.CASCADE)
    protocol_city = models.CharField(
        'Город в протоколе', help_text="г. Бишкек", max_length=255, null=True,
        blank=True)
    protocol_date = models.DateField('Дата протокола', null=True, blank=True)
    protocol_question = models.TextField('Рассмотрели вопросы', null=True,
                                         blank=True,
                                         help_text='РАССМАТРИВАЕМЫЙ ВОПРОС')
    protocol_decision = models.TextField('Приняли решение', null=True,
                                         blank=True,
                                         help_text='РАССМОТРЕЛ ВОПРОС И РЕШИЛ')
    protocol_chairman = models.TextField('Председатель Правление Кооператива',
                                         null=True, blank=True, )

    def __str__(self):
        return f'{self.id}'

protocols/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import SelectMultiple

from protocols.models import UserProtocol
from users.models import CustomUser


class ProtocolCreateForm(forms.ModelForm):
    users_presented = forms.ModelMultipleChoiceField(
        label='Список присутствовавших',
        queryset=CustomUser.objects.filter(
            user_is_operator=False, is_staff=False),
        required=False,
        widget=SelectMultiple(
            attrs={'class': 'form-control'}
        ))

    users_accepted = forms.ModelMultipleChoiceField(
        label='Список принявших решение',
        queryset=CustomUser.objects.filter(
            user_is_operator=False, is_staff=False),
        required=False,
        widget=SelectMultiple(
            attrs={'class': 'form-control'}
        ))

    class Meta(UserCreationForm.Meta):
        model = UserProtocol
        fields = ('users_presented', 'users_accepted', 'protocol_city', 'protocol_date', 'protocol_question',
                  'protocol_decision', 'protocol_chairman')

protocols/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView

from protocols.forms import ProtocolCreateForm
from protocols.models import UserProtocol


class ProtocolListView(UserPassesTestMixin, ListView):
    model = UserProtocol
    template_name = 'protocols/protocol_list.html'
    paginate_by = 30

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.user_is_operator

    def get_queryset(self):
        object_list = UserProtocol.objects.all().order_by('-id')

        return object_list


class ProtocolCreateView(UserPassesTestMixin, CreateView):
    model = UserProtocol
    template_name = 'protocols/protocol_create.html'
    form_class = ProtocolCreateForm
    success_url = reverse_lazy('protocol_list')

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.user_is_operator

    def form_valid(self, form):
        form.instance.protocol_created_user = self.request.user
        return super().form_valid(form)


class ProtocolDetailView(UserPassesTestMixin, DetailView):
    model = UserProtocol
    template_name = 'protocols/protocol.html'

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.user_is_operator


class ProtocolUpdateView(UserPassesTestMixin, UpdateView):
    model = UserProtocol
    template_name = 'protocols/protocol_update.html'
    form_class = ProtocolCreateForm
    success_url = reverse_lazy('protocol_list')

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.user_is_operator

templates/protocols/protocol.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Решение | Келечек - Жилищный кооператив Кыргызстан, Бишкек</title>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords"
        content="Жилищный кооператив, доступное жилье в Бишкеке, Келечек кооператив, Жилищный кооператив Келечек, Жилищный кооператив, Жилищный кооператив Бишкек, Жилищный кооператив Кыргызстан, Недвижимость, Недвижимость в рассрочку, Альтернатива ипотеке, Жилье в аренду в Бишкеке">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google-site-verification" content="c_11ijAMXTEgBWYztyw9vgf31T3ktXLRsKKTdCzmzJY" />
    <!-- favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo/favicon.png' %}">
</head>
<!DOCTYPE html>

<body>
    <style>
        .title2 {
            text-align: center;
            font-weight: bold;
            margin: 10px 0;
        }

        p {
            margin: 0;
        }
    </style>
    <p align="center">
    <h3 style="text-align: center;">Некоммерческий жилищно-накопительный кооператив взаимопомощи <br>
        «ОДИН ШАГ К БУДУЩЕМУ»</h3>
    </p>

    <h3 style="text-align: center; margin-top:50px">РЕШЕНИЕ № {{object.id}}</h3>
    <h3 style="text-align: center;">ПРАВЛЕНИЕ КООПЕРАТИВА</h3>

    <p>
        {% if object.protocol_city %}{{object.protocol_city}}{% else %}г.Бишкек {% endif %}
        <span style="float: right;">{{object.protocol_date}}</span>
    </p>
    <p style="margin-bottom: 50px;"></p>
    <p align="center">
    <h3 style="text-align: center;">РАССМАТРИВАЕМЫЙ ВОПРОС:</h3>
    </p>
    <br>
    <p style="text-align:center">
        {{object.protocol_question}}
    </p>
    <br>
    <h3 style="text-align: center;">РАССМОТРЕЛ ВОПРОС И РЕШИЛ: </h3>
    </p>
    <br>
    <p style="text-align:center">
        {{object.protocol_decision}}
    </p>
    <br>

    <p>
        {% if object.protocol_chairman %}
        <b>{{object.protocol_chairman}}</b>
        {% else %}
        <strong>Председатель Правление Кооператива </strong> <span style="margin: 0 10px;"> ___________________</span>
        <strong style="">
            Курманалиев Э.К.</strong>
        {% endif %}
    </p>
    <br>
</body>

</html>

templates/protocols/protocol_create.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}

{% block title %}Создать решение | {% endblock %}
{% block content %}
<!-- Start breadcumb Area -->
<div class="page-area">
    <div class="breadcumb-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="breadcrumb">
                    <div class="bread-inner">
                        <div class="section-headline white-headline">
                            <h2>Создать решение</h2>
                        </div>
                        <ul class="breadcrumb-bg">
                            <li class="home-bread"><a href="{% url 'home' %}">Главная</a></li>
                            <li>Создать решение</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcumb Area -->


<div class="container p-tb-2">
    <form id="post_form" method="post" action="" enctype="multipart/form-data">
        <div class="col-md-6">
            {% csrf_token %}
            <div id="div_id_protocol_date" class="form-group">
                <label for="id_protocol_date" class="">
                    Дата решения
                </label>
                <div class="">
                    <input type="date" name="protocol_date" value="{{object.protocol_date|date:'Y-m-d' }}"
                        class="dateinput form-control" id="id_protocol_date">
                </div>
            </div>
            {{form.protocol_question|as_crispy_field}}
            <input type="submit" name="submit" value="Создать" class="btn btn-success">


        </div>
        <div class="col-md-6">
            {{form.protocol_city|as_crispy_field }}
            {{form.protocol_decision|as_crispy_field}}
        </div>
    </form>
</div>
{% endblock %}

templates/protocols/protocol_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Список договоров | {% endblock %}
{% block content %}
<!-- Start breadcumb Area -->
<div class="page-area">
    <div class="breadcumb-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="breadcrumb">
                    <div class="bread-inner">
                        <div class="section-headline white-headline">
                            <h2>Список протоколов</h2>
                        </div>
                        <ul class="breadcrumb-bg">
                            <li class="home-bread"><a href="{% url 'home' %}">Главная</a></li>
                            <li>Список протоколов</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcumb Area -->

<style>
    .font-size-50 {
        font-size: 50px;
    }

    .list-button a {
        margin-bottom: 5px;
    }
</style>

<div class="container p-tb-2">
    <div class="row">
        <div class="well-inner">
            <a href="{% url 'protocol_create' %}" class="btn btn-primary" style="margin-bottom: 20px">Создать
                протокол</a>

            <table class="table table-bordered table-hover toggle-circle" id="exampleFootableFiltering">
                <thead>
                    <tr>
                        <th>№</th>
                        <th>Дата</th>
                        <th>Управление</th>
                    </tr>
                </thead>
                {% for protocol in object_list %}
                <tr>
                    <td>{{protocol.id}}</td>
                    <td>{{protocol.protocol_date}}</td>
                    <td>
                        <a target="_blank" href="{% url 'protocol_detail' protocol.pk %}"
                            class="btn btn-primary">Подробнее</a>
                        {% if user.is_superuser %}
                        <a target="_blank" href="{% url 'protocol_update' protocol.pk %}"
                            class="btn btn-success">Изменить</a>
                        {% endif %}

                    </td>
                </tr>
                {% endfor %}
            </table>


        </div>
    </div>
    <!-- Start Paginator -->
    <div class="col-md-12 col-sm-12 col-xs-12">
        {% if is_paginated %}
        <div class="blog-pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                {% else %}
                <li class="disabled"><span>Prev</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span>
                </li>
                {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
                {% else %}
                <li class="disabled"><span>Next</span></li>
                {% endif %}
            </ul>
        </div>
        {% endif %}
    </div>
    <!-- End Paginator -->
</div>
{% endblock %}

templates/protocols/protocol_update.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}
{% block title %}Создать решение | {% endblock %}
{% block content %}
<!-- Start breadcumb Area -->
<div class="page-area">
    <div class="breadcumb-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="breadcrumb">
                    <div class="bread-inner">
                        <div class="section-headline white-headline">
                            <h2>Изменить решение</h2>
                        </div>
                        <ul class="breadcrumb-bg">
                            <li class="home-bread"><a href="{% url 'home' %}">Главная</a></li>
                            <li>Изменить решение</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcumb Area -->


<div class="container p-tb-2">
    <form id="post_form" method="post" action="" enctype="multipart/form-data">
        <div class="col-md-6">
            {% csrf_token %}
            <div id="div_id_protocol_date" class="form-group">
                <label for="id_protocol_date" class="">
                    Дата решения
                </label>
                <div class="">
                    <input type="date" name="protocol_date" value="{{object.protocol_date|date:'Y-m-d' }}"
                        class="dateinput form-control" id="id_protocol_date">
                </div>
            </div>
            {{form.protocol_question|as_crispy_field}}
            <input type="submit" name="submit" value="Изменить" class="btn btn-success">


        </div>
        <div class="col-md-6">
            {{form.protocol_city|as_crispy_field }}
            {{form.protocol_decision|as_crispy_field}}
            {{form.protocol_chairman|as_crispy_field}}
        </div>
    </form>
</div>

{% endblock %}