ads/urls.py
from django.urls import path
from ads.views import (AdsCreateView, AdsListView,
                       AdsDetailView, AdsDeleteView, AdsUpdateView, AdsTableView, make_hot, up_ad, AdsUncheckedListView,
                       change_status)

urlpatterns = [
    path('ads_list/', AdsListView.as_view(), name='ads_list'),
    path('ads_unchecked/', AdsUncheckedListView.as_view(), name='ads_unchecked'),
    path('ads_table/', AdsTableView.as_view(), name='ads_table'),
    path('ads_create/', AdsCreateView.as_view(), name='ads_create'),
    path('ads_detail/<int:pk>/', AdsDetailView.as_view(), name='ads_detail'),
    path('ads_delete/<int:pk>/', AdsDeleteView.as_view(), name='ads_delete'),
    path('ads_update/<int:pk>/', AdsUpdateView.as_view(), name='ads_update'),
    path('make_hot/<int:pk>/', make_hot, name='make_hot'),
    path('up_ad/<int:pk>/', up_ad, name='up_ad'),
    path('change_status/<int:pk>/', change_status, name='change_status'),
]

kelechek_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from kelechek_project import settings

urlpatterns = [
    path('upr/admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('api/kelechek/', include('api.urls')),
    path('api/kelechek/rest-auth/', include('dj_rest_auth.urls')),
    path('', include('pages.urls')),
    path('', include('news.urls')),
    path('', include('faq.urls')),
    path('', include('ads.urls')),
    path('votes/', include('quotes.urls')),
    path('protocols/', include('protocols.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATICFILES_DIRS)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.error_404_view'

quotes/urls.py
from django.urls import path

from quotes.views import (
    votes_list, results, vote, detail, VoteCreateView,
    VoteUpdateView, VoteDeleteView
)

app_name = 'quotes'
urlpatterns = [
    path('', votes_list, name='votes'),
    path('<int:question_id>/', detail, name='detail'),
    path('<int:question_id>/results/', results, name='results'),
    path('<int:question_id>/vote/', vote, name='vote'),
    path('create/', VoteCreateView.as_view(), name='vote_create'),
    path('update/<int:pk>', VoteUpdateView.as_view(),
         name='vote_update'),
    path('delete/<int:pk>', VoteDeleteView.as_view(),
         name='vote_delete'),
]

templates/votes/create.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}
{% block title %}Опубликовать объявление | {% endblock %}
{% block content %}
<!-- Start breadcumb Area -->
<div class="page-area">
    <div class="breadcumb-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="breadcrumb">
                    <div class="bread-inner">
                        <div class="section-headline white-headline">
                            <h2>Опубликовать голосование</h2>
                        </div>
                        <ul class="breadcrumb-bg">
                            <li class="home-bread"><a href="{% url 'home' %}">Главная</a></li>
                            <li>Голосование</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcumb Area -->


<div class="container p-tb-2">
    <div class="col-md-12">
        <form id="post_form" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-md-6">
                {{ form.question_number|as_crispy_field }}
                {{ form.question_name|as_crispy_field }}
            </div>
            <div class="col-md-6">
                {{ form.question_city|as_crispy_field }}
                <div id="question_date" class="form-group">
                    <label for="id_question_date" class="">
                        Дата протокола
                    </label>
                    <div class="">
                        <input type="date" name="question_date" value="{{form.question_date|date:'Y-m-d' }}"
                            class="dateinput form-control" id="id_question_date">
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                {{ form.question_adr|as_crispy_field }}
                {{ form.question_text_1|as_crispy_field }}
                {{ form.question_text_2|as_crispy_field }}
                {{ form.question_text_3|as_crispy_field }}
                {{ form.question_file|as_crispy_field }}


                {% crispy form %}
                <input type="submit" name="submit" value="Опубликовать">
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/votes/delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Start breadcumb Area -->
<div class="page-area">
    <div class="breadcumb-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="breadcrumb">
                    <div class="bread-inner">
                        <div class="section-headline white-headline">
                            <h2>Удаление голосования</h2>
                        </div>
                        <ul class="breadcrumb-bg">
                            <li class="home-bread">Главная</li>
                            <li><a href="{% url 'admin_page' %}">Панель управления</a></li>
                            <li><a href="{% url 'quotes:votes' %}">Голосование</a></li>
                            <li>{{ object.question_name}}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcumb Area -->

<div class="container p-tb-2">
    <form method="post" action="{% url 'quotes:vote_delete' object.pk %}">
        {% csrf_token %}
        <h2>Вы действительно хотите удалить "{{ object.question_name }}" ?</h2>
        <button class="btn btn-danger" type="submit">Удалить</button>
    </form>
</div>

{% endblock %}

templates/votes/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Start breadcumb Area -->
<div class="page-area">
    <div class="breadcumb-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="breadcrumb">
                    <div class="bread-inner">
                        <ul class="breadcrumb-bg">
                            <li class="home-bread"><a href="{% url 'home' %}">Главная</a></li>
                            <li class="bread"><a href="{% url 'admin_page' %}">Панель управления</a></li>
                            <li>Результат голосования</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcumb Area -->
<div class="container">
    <div class="row mar-row">
        <div class="project-feature">
            <!-- Start column -->
            <div class="col-md-7 col-sm-6 col-xs-12">
                <div class="row project-wrapper">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="single-project-inner">
                            <div class="project-inner">
                                <div class="project-text">
                                    <h4>Вопрос: {{ question.question_name }}</h4>
                                    {% if question.question_file %}
                                        <p>Скачать файл <a href="{{ question.question_file.url }}">Скачать</a></p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="single-project-inner user-list">
                            {% for choice in question.choice_set.all %}
                                <tr>

                                    <td>{{ choice.choice_text }} </td>
                                    <td><span class ="badge badge-success float-right">
                                        {{ choice.votes }} голос
                                        {{ choice.голосов | pluralize }}</span> | </td>
                                </tr>
                            {% endfor %}
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th scope="col">ФИО</th>
                                    <th scope="col">Ответ</th>
                                </tr>
                                {% for user in question.users.all %}
                                <tr>

                                    <td>{{ user.user_full_name }} </td>
                                    <td>
                                        {% for choice in user.choice_set.all %}
                                            {{ choice }}
                                        {% endfor %}
                                    </td>
                                </tr>
                                {% endfor %}
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End column -->
        </div>
    </div>
</div>
{% endblock %}

templates/votes/formset.html
{% load crispy_forms_tags static %}

{{ formset.management_form|crispy }}
<br>

    {% for form in formset.forms %}
            <div class="col-md-4">
                {% for field in form.visible_fields %}
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field|as_crispy_field }}
                {% endfor %}
            </div>
    {% endfor %}


<br>

templates/votes/pdf_template.html
<html>
<head>
  <title>Результат голосования за {{ question.question_date }}</title>
  <style>
    .text-center {
        text-align: center;
    }
    .font-size-20 {
        font-size: 20px;
    }

    .mb-20 {
        margin-bottom: 20px;
    }

    .m-20 {
        margin: 0 20px;
    }

    #customers {
      font-family: Arial, Helvetica, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }

    #customers td, #customers th {
      border: 1px solid #ddd;
      padding: 8px;
    }

    #customers th {
      padding-top: 12px;
      padding-bottom: 12px;
      text-align: left;
      background-color: #9E9E9E;
      color: white;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="row mar-row">
        <div class="project-feature">
            <!-- Start column -->
            <div class="col-md-7 col-sm-6 col-xs-12">
                <div class="row project-wrapper">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="single-project-inner">
                            <div class="project-inner">
                                <div class="text-center">
                                    <h2>Вопрос:
                                        {{ question.question_name }}</h2>
                                </div>
                            </div>
                        </div>
                        <div class="single-project-inner user-list">
                            <div class="text-center">
                                {% for choice in question.choice_set.all %}
                                    <tr>
                                        <td>
                                            <b class="font-size-20">{{ choice.choice_text }}</b>:
                                        </td>
                                        <td><span class="float-right font-size-20">
                                            {{ choice.votes }} голос
                                            {{ choice.голосов | pluralize }}</span> <span class="m-20">|</span> </td>
                                    </tr>
                                {% endfor %}
                            </div>
                            <hr class="mb-20">
                            <table id="customers" class="table table-hover">
                                <thead>
                                    <tr>
                                        <th scope="col">ФИО</th>
                                        <th scope="col">Ответ</th>
                                    </tr>
                                </thead>

                                {% for user in question.users.all %}
                                <tr>
                                    <td style="width: 300px">{{ user.user_full_name }}
                                    </td>
                                    <td>
                                        {% for choice in user.choice_set.all %}
                                            {{ choice }}
                                        {% endfor %}
                                    </td>
                                </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End column -->
        </div>
    </div>
</div>
</body>
</html>

templates/votes/results.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<div class="row" style="margin: 10% 0;">
    <h1 class ="mb-5 text-center">Вы успешно проголосовали!</h1>
    <span class="text-center" style="display: block">
        <a class ="btn btn-info " href ="{% url 'user_detail' user.pk %}">Вернутся назад</a>
    </span>
</div>
</div>
{% endblock %}

templates/votes/update.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}
{% block title %}Опубликовать объявление | {% endblock %}
{% block content %}
    <!-- Start breadcumb Area -->
    <div class="page-area">
        <div class="breadcumb-overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="breadcrumb">
                        <div class="bread-inner">
                            <div class="section-headline white-headline">
                                <h2>Опубликовать голосование</h2>
                            </div>
                            <ul class="breadcrumb-bg">
                                <li class="home-bread"><a href="{% url 'home' %}">Главная</a></li>
                                <li>Голосование</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End breadcumb Area -->


    <div class="container p-tb-2">
        <div class="col-md-12">
            <form id="post_form" method="post" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col-md-9">
                    {% crispy form %}
                    <input type="submit" name="submit" value="Опубликовать">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/votes/vote_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Start breadcumb Area -->
<div class="page-area">
    <div class="breadcumb-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="breadcrumb">
                    <div class="bread-inner">
                        <ul class="breadcrumb-bg">
                            <li class="home-bread"><a href="{% url 'home' %}">Главная</a></li>
                            <li class="bread"><a href="{% url 'user_detail' user.pk %}">Профиль</a></li>
                            <li>Результат голосования</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcumb Area -->
<div class="container" style="margin-top: 100px">
    {% if request.user not in question.users.all %}
    <h4>Название вопроса: {{ question.question_name }}</h4>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <h4 style="color: red;">{{ message }}</h4>
        {% endfor %}
    </ul>
    {% endif %}
    <form action="{% url 'quotes:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
        <div class="form-check">
            <input type="radio" name="choice" class="form-check-input" id="choice{{ forloop.counter }}"
                value="{{ choice.id }}" />
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
        </div>
        {% endfor %}
        <input type="submit" value="Проголосовать" class="btn btn-success btn-lg btn-block mt-4" />
    </form>
    {% else %}
    <h4 class="center" style="color: red">Ваш голос засчитан!</h4>
    <div class="center">
        {% for choice in question.choice_set.all %}
        <tr>

            <td>{{ choice.choice_text }} </td>
            <td><span class="badge badge-success float-right">
                    {{ choice.votes }} голос
                    {{ choice.голосов | pluralize }}</span> | </td>
        </tr>
        {% endfor %}
    </div>
    {% endif %}
    {% if question.question_file %}
        <hr style="border-bottom: 3px solid black">
        <h3><a href="{{question.question_file.url}}">Скачать: Протокол № {{question.question_number}}</a></h3>
    {% endif %}
    <hr style="margin-bottom: 10%; border-bottom: 3px solid black">
    {% include 'votes/vote_document.html' %}
</div>
{% endblock %}

templates/votes/vote_document.html
 <style>
        .center {
            text-align: center;
            color: black;
        }
        .title {
            font-size: 20px;
            font-weight: bold;
        }
        .sub-title {
            font-size: 16px;
        }
        .bold {
            font-weight: bold;
            color: black;

        }

        .mg-10 {
            margin: 10px 0 20px;
        }

        .mb-40 {
            margin-bottom: 40px;
        }
        .mt-20 {
            margin-top: 20px;
        }
        p {
            color: black;
        }
</style>
    <p class="center title">ПРОТОКОЛ № {{ question.question_number }} </p>
    <p class="center sub-title">Общего собрания членов</p>
    <h4 class="center">Некоммерческий жилищно-накопительный кооператив взаимопомощи <br>
    «Келечекке Бир Кадам»
    </h4>

    <p class="bold">
        {% if question.question_city %}{{ question.question_city }}
        {% else %}г. Бишкек{% endif %}
        <span
            style="float: right;
">{{ question.question_date}}</span></p>
    <p style="margin-bottom: 50px;"></p>


    <h5 class="bold">
        Место проведения общего собрания: {{ question.question_adr}}
    </h5>
    <p class="bold">Время начало: _____________</p>
    <p class="bold">Время окончания: __________</p>


    <p>Общее количество членов Кооператива: ________________ </p>
    <p>Количество присутствующих членов Кооператива: ________</p>
    <p>Кворум для принятия решения соблюден.</p>
    {% for choice in question.choice_set.all %}
        <tr>

            <td>{{ choice.choice_text }} </td>
            <td><span class="float-right">
                {{ choice.votes }}
                {{ choice.голосов | pluralize }}</span> | </td>
        </tr>
    {% endfor %}
    </p>


    <p class="center sub-title">Присутствовали</p>
    <p>{{ users_count }} человек</p>
    <br class="mt-20">


    <p style="text-align:center">{{object.protocol_question}}</p>
    <p class="sub-title">Кворум имеется 100%.</p>
    <br>


    <p class="center sub-title bold">ПОВЕСТКА ДНЯ:</p>
    <p><span style="margin-right: 20px"></span>
        {{ question.question_text_1|safe}}</p>


    <p class="center sub-title bold">ПРОТОКОЛ:</p>
    <p><span style="margin-right: 20px"></span>
        {{ question.question_text_2|safe}}</p>
    <br>


    <p class="center sub-title bold">ПОСЛЕ ОБСУЖДЕНИЯ ПОВЕСТКИ ДНЯ, ПРИСУТСТВУЮЩИЕ ЕДИНОГЛАСНО РЕШИЛИ:</p>
    <p>
        <span style="margin-right: 20px"></span> {{ question.question_text_3|safe}}
    </p>
    <br>


    <p>3
        <strong>Председатель правления кооператива </strong>
        <span style="margin: 0 10px;"> ______________________________________</span>
        <strong style="">
            Курманалиев Э.К.</strong>
    </p>
    <p>
        <strong>Секретарь правления кооператива </strong>
        <span style="margin: 0 10px 0 38px;">
            ______________________________________</span>
        <strong style="">
            Ажыбеков А.Н.</strong>
    </p>
    <br><br>

    <p>Протокол скрепляется печатью Кооператива. В случае отсутствия печати подписи
    председателя и секретаря свидетельствуются нотариально.</p><br><br><br><br>
<br>

templates/votes/votes_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Start breadcumb Area -->
<div class="page-area">
    <div class="breadcumb-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="breadcrumb">
                    <div class="bread-inner">
                        <div class="section-headline white-headline">
                            <h2>Список вопросов</h2>
                        </div>
                        <ul class="breadcrumb-bg">
                            <li class="home-bread"><a href="{% url 'home' %}">Главная</a></li>
                            <li><a href="{% url 'admin_page' %}">Панель управления</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcumb Area -->

<!-- Panel Filtering rows -->
<div class="panel p-tb-2">
    <div class="panel-body">
        <div class="btn-block" style="text-align: right; padding: 2vh 4vw;">
            <a href="{% url 'quotes:vote_create' %}" class="btn btn-success"
                style="text-transform: uppercase; font-weight:
                bold">Добавить вопрос</a>
        </div>
        <table class="center-align table table-bordered table-hover toggle-circle">


            <thead>
                <th class="center-align" data-name="id" data-type="number" data-breakpoints="xs" width="3%">№</th>
                <th data-name="login" class="center-align">Вопрос</th>
                <th data-name="login" class="center-align">Дата создания</th>
                <th data-name="management" width="9%" class="center-align">Управление</th>
                </tr>
            </thead>
            <tbody>
                {% for question in question_list %}
                <tr>
                    <td class="center-align">
                        {{ question.question_number }}</td>
                    <td class="center-align">{{ question.question_name }}</td>
                    <td class="center-align">{{ question.pub_date }}</td>
                    <td class="center-align">
                        <a href="{% url 'quotes:detail' question.pk %}"
                            style="background:#03bfe2; color:#fff; font-weight:700; font-size:13px; padding:4px 10px; border-radius: 6px;"><i
                                class="fa fa-desktop"></i></a>
                        <a href="{% url 'quotes:vote' question.pk %}"
                            style="background:#03bfe2; color:#fff; font-weight:700; font-size:13px; padding:4px 10px; border-radius: 6px;"><i
                                class="fa fa-user"></i></a>
                        <a href="{% url 'quotes:vote_update' question.pk %}"
                            style="background:#03bfe2; color:#fff; font-weight:700; font-size:13px; padding:4px 10px; border-radius: 6px;"><i
                                class="fa fa-gears"></i></a>
                        <a href="{% url 'quotes:vote_delete' question.pk %}"
                            style="background:#03bfe2; color:#fff; font-weight:700; font-size:13px; padding:4px 10px; border-radius: 6px;"><i
                                class="fa fa-trash"></i></a>

                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <!-- Start Paginator -->
        <div class="col-md-12 col-sm-12 col-xs-12">
            {% if is_paginated %}
            <div class="blog-pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                    {% else %}
                    <li class="disabled"><span>Prev</span></li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span>
                    </li>
                    {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
                    {% else %}
                    <li class="disabled"><span>Next</span></li>
                    {% endif %}
                </ul>
            </div>
            {% endif %}
        </div>
        <!-- End Paginator -->
    </div>
</div>
<!-- End Panel Filtering -->


{% endblock %}