ads/urls.py
from django.urls import path
from ads.views import (AdsCreateView, AdsListView,
                       AdsDetailView, AdsDeleteView, AdsUpdateView, AdsTableView, make_hot, up_ad, AdsUncheckedListView,
                       change_status)

urlpatterns = [
    path('ads_list/', AdsListView.as_view(), name='ads_list'),
    path('ads_unchecked/', AdsUncheckedListView.as_view(), name='ads_unchecked'),
    path('ads_table/', AdsTableView.as_view(), name='ads_table'),
    path('ads_create/', AdsCreateView.as_view(), name='ads_create'),
    path('ads_detail/<int:pk>/', AdsDetailView.as_view(), name='ads_detail'),
    path('ads_delete/<int:pk>/', AdsDeleteView.as_view(), name='ads_delete'),
    path('ads_update/<int:pk>/', AdsUpdateView.as_view(), name='ads_update'),
    path('make_hot/<int:pk>/', make_hot, name='make_hot'),
    path('up_ad/<int:pk>/', up_ad, name='up_ad'),
    path('change_status/<int:pk>/', change_status, name='change_status'),
]

kelechek_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from kelechek_project import settings

urlpatterns = [
    path('upr/admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('api/kelechek/', include('api.urls')),
    path('api/kelechek/rest-auth/', include('dj_rest_auth.urls')),
    path('', include('pages.urls')),
    path('', include('news.urls')),
    path('', include('faq.urls')),
    path('', include('ads.urls')),
    path('votes/', include('quotes.urls')),
    path('protocols/', include('protocols.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATICFILES_DIRS)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.error_404_view'

quotes/urls.py
from django.urls import path

from quotes.views import (
    votes_list, results, vote, detail, VoteCreateView,
    VoteUpdateView, VoteDeleteView
)

app_name = 'quotes'
urlpatterns = [
    path('', votes_list, name='votes'),
    path('<int:question_id>/', detail, name='detail'),
    path('<int:question_id>/results/', results, name='results'),
    path('<int:question_id>/vote/', vote, name='vote'),
    path('create/', VoteCreateView.as_view(), name='vote_create'),
    path('update/<int:pk>', VoteUpdateView.as_view(),
         name='vote_update'),
    path('delete/<int:pk>', VoteDeleteView.as_view(),
         name='vote_delete'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views
from users.views import (UserListView, UserGivenView, UserDetail,
                         UserUpdateView, UserDeleteView,
                         user_to_delete_list, SignUpView, login_success,
                         AgreementListView, Agreement1, Agreement2,
                         Agreement3, Agreement4, Agreement5, Agreement_1,
                         Agreement_2, AgreementPrilojenie3,
                         AgreementCreateView, Agreement1UpdateView,
                         Agreement2UpdateView, Agreement3UpdateView,
                         Agreement4UpdateView, Agreement5UpdateView,
                         Agreement_1UpdateView, OperatorSignUp,
                         OperatorsList, user_password_reset, NotificationList,
                         NotificationCreate, NotificationDelete)

urlpatterns = [
    path('users/', UserListView.as_view(), name='users_list'),
    path('users_given_list/', UserGivenView.as_view(), name='users_given_list'),
    path('user/<int:pk>', UserDetail.as_view(), name='user_detail'),
    path('user/<int:pk>/update', UserUpdateView.as_view(), name='user_update'),
    path('user/<int:pk>/delete', UserDeleteView.as_view(), name='user_delete'),
    path('delete/<int:pk>/', user_to_delete_list, name='delete'),
    path('user/create', SignUpView.as_view(), name='signup'),
    path('login_success/', login_success, name='login_success'),
    path('user/<int:pk>/agreement-list/', AgreementListView.as_view(), name='agreement_list'),
    path('user/<int:pk>/dogovor-ob-uchastii/', Agreement1.as_view(), name='agreement_1'),
    path('user/<int:pk>/dogovor-ssudy/', Agreement2.as_view(), name='agreement_2'),
    path('user/<int:pk>/prilojenie/', Agreement3.as_view(), name='agreement_3'),
    path('user/<int:pk>/prilojenie3/', AgreementPrilojenie3.as_view(),
         name='agreement_prilojenie_3'),
    path('user/<int:pk>/dogovor-o-zaloge/', Agreement4.as_view(), name='agreement_4'),
    path('user/<int:pk>/anketa/', Agreement5.as_view(), name='agreement_5'),
    path('user/<int:pk>/agreement-create/', AgreementCreateView.as_view(), name='agreement_create'),

    # Agreemt update
    path('user/<int:pk>/dogovor-ob-uchastii-update/', Agreement1UpdateView.as_view(), name='agreement1_update'),
    path('user/<int:pk>/dogovor-ssudy-update/', Agreement2UpdateView.as_view(), name='agreement2_update'),
    path('user/<int:pk>/prilojenie-update/', Agreement3UpdateView.as_view(), name='agreement3_update'),
    path('user/<int:pk>/dogovor-o-zaloge-update/', Agreement4UpdateView.as_view(), name='agreement4_update'),
    path('user/<int:pk>/anketa-update/', Agreement5UpdateView.as_view(), name='agreement5_update'),

    # Prilojenie
    path('user/<int:pk>/prilojenie-1/', Agreement_1.as_view(), name='agr_1'),
    path('user/<int:pk>/prilojenie-1-update/', Agreement_1UpdateView.as_view(), name='agr_1_update'),
    path('user/<int:pk>/prilojenie-2/', Agreement_2.as_view(), name='agr_2'),

    path('operator/create/', OperatorSignUp.as_view(), name='operator_signup'),
    path('operators/', OperatorsList.as_view(), name='operators_list'),
    path('operators/notification', NotificationList.as_view(), name='notification_list'),
    path('operator/notification/create/', NotificationCreate.as_view(), name='notification_create'),
    path('operator/notification/delete/<int:pk>', NotificationDelete.as_view(), name='notification_delete'),

    path('user/<int:pk>/reset_password/', user_password_reset, name='reset_user_password'),
]

users/models.py
import time

from django.contrib.auth.models import AbstractUser
from django.db import models, transaction
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver

from region.models import UserRegion

BOOKKEEPER_CHOICE = [
    ('Первоначальный взнос', 'Первоначальный взнос'),
    ('Пополнение', 'Пополнение'),
    ('Вступительный взнос', 'Вступительный взнос'),
    ('Погашение ссуды', 'Погашение ссуды'),
]


class CustomUser(AbstractUser):
    username = models.CharField(verbose_name='Номер паспорта',
                                max_length=255, unique=True)
    user_full_name = models.CharField(max_length=150,
                                      verbose_name='ФИО',
                                      blank=True, null=True)
    user_full_name_plural = models.CharField(max_length=150,
                                             verbose_name='ФИО в Родительском падеже',
                                             blank=True, null=True)
    user_passport_given_by = models.CharField(max_length=30,
                                              verbose_name='Выдан кем')
    user_passport_from_date = models.DateField(verbose_name='Выдан от',
                                               blank=True, null=True)
    user_inn = models.CharField(max_length=20, verbose_name='ИНН')
    user_birthday = models.DateField(verbose_name='День рождения',
                                     blank=True, null=True)
    user_birthday_city = models.CharField(max_length=200,
                                          verbose_name='Место рождения')
    user_passport_address = models.CharField(max_length=200,
                                             verbose_name='Адрес по прописке')
    user_real_address = models.CharField(max_length=200,
                                         verbose_name='Фактический адрес проживания')
    user_phone_number1 = models.CharField(max_length=255,
                                          verbose_name='Номер телефона 1')
    user_phone_number2 = models.CharField(max_length=255,
                                          verbose_name='Номер телефона 2',
                                          null=True, blank=True)
    user_registration_date = models.DateTimeField('Дата регистрации',
                                                  auto_now_add=True,
                                                  blank=True,
                                                  null=True)
    # status if user is an operator
    user_is_operator = models.BooleanField(default=False,
                                           verbose_name='Статус оператора')
    is_moderator = models.BooleanField('Статус модератора', default=False)
    is_bookkeeper = models.BooleanField('Статус бухгалтера', default=False)
    # status if user has already got the property
    user_is_queued = models.BooleanField(default=True,
                                         verbose_name='Пользователь в Очереди')
    user_balance = models.CharField(max_length=50, verbose_name='Баланс',
                                    blank=True, null=True)
    user_position = models.IntegerField(verbose_name='Позиция',
                                        blank=True, null=True, default=1)
    user_notifications = models.TextField(verbose_name='Оповещения',
                                          blank=True, null=True)
    user_agreement = models.ForeignKey('UserAgreement',
                                       on_delete=models.CASCADE,
                                       null=True, blank=True,
                                       related_name='agreement_user_model')
    user_region = models.ForeignKey(UserRegion,
                                    on_delete=models.CASCADE,
                                    related_name='region_for_user',
                                    null=True, blank=True)
    user_is_delete = models.BooleanField(default=False,
                                         verbose_name='Пользователь удален')
    update_at = models.DateTimeField('Дата послендего изменения',
                                     auto_now=True, null=True, blank=True)

    def __str__(self):
        result = ''
        last_name = (
            self.user_full_name.split()
            if self.user_full_name
            else self.user_full_name)
        try:
            if last_name:
                if len(last_name) == 3:
                    result = f'{last_name[0]} {last_name[1][0]}. {last_name[2][0]}.'
                elif len(last_name) == 2:
                    result = f'{last_name[0]} {last_name[1][0]}.'
        except:
            result = f'{last_name[0]}' if last_name[0] else last_name
        return result

    def clean(self):
        self.username = self.username.lower()


class UserAgreement(models.Model):
    agreement_city = models.CharField('Город договора', max_length=255,
                                      help_text='пример: г. Бишкек',
                                      null=True, blank=True)
    agreement_by_whom = models.TextField('В лице от кооператива',
                                         null=True, blank=True)
    agreement_date = models.DateField('Дата Договора об участии',
                                      null=True, blank=True)
    agreement_document_number = models.IntegerField('№ Договора об участии',
                                                    null=True, blank=True)
    agreement_amount = models.CharField('ссуда на сумму', max_length=255,
                                        help_text="787 500",
                                        null=True, blank=True)
    agreement_amount_text = models.CharField('ссуда на сумму в виде текста',
                                             null=True, blank=True,
                                             help_text="Семьсот восемьдесят семь тысяч пятьсот",
                                             max_length=255)
    agreement_month = models.IntegerField('Месяцев на ссуду',
                                          help_text='120', default=0,
                                          null=True, blank=True)
    agreement_month_text = models.CharField('Месяцев на ссуду в виде текста',
                                            help_text='сто двадцать',
                                            max_length=255,
                                            null=True, blank=True)
    agreement_home = models.TextField('Залоговое имущество',
                                      null=True, blank=True,
                                      help_text='''Квартира, полезной площадью 34,1 кв.м., 
                                    жилой площадью 18,2 кв.м., находящийся по адресу''')
    agreement_purchase = models.CharField('Договор купли-продажи №',
                                          max_length=255,
                                          null=True, blank=True)
    agreement_purchase_date = models.DateField('Дата Договора купли-продажи',
                                               null=True, blank=True)
    agreement_chairman = models.CharField(verbose_name='В лице Председателя',
                                          max_length=255, null=True,
                                          blank=True,
                                          help_text='в лице Председателя Правления Курманалиева Эламана Курманалиевича')
    agreement_chairman2 = models.CharField(verbose_name='В лице Председателя',
                                           max_length=255, null=True,
                                           blank=True,
                                           help_text='''в лице Председателя Правления 
                                    Курманалиева Эламана Курманалиевича''')
    home_price = models.IntegerField(default=0,
                                     verbose_name='Желаемая стоимость',
                                     help_text='Желаемая стоимость недвижимого имущества')
    home_month_price = models.IntegerField(default=0,
                                           help_text='Член кооператива оплачивает сумму в размере',
                                           verbose_name='Оплачиваемся сумма')
    home_price_text = models.CharField(max_length=255,
                                       verbose_name='Желаемая стоимость в письменном виде',
                                       help_text='''Желаемая стоимость недвижимого 
                                    имущества в письменном виде (два миллиона сомов)''')
    home_price_25percent_text = models.CharField(max_length=255,
                                                 verbose_name='25% от общей суммы в письменном виде',
                                                 help_text='25% от общей суммы в письменном виде')
    home_price_4percent_text = models.CharField(max_length=255,
                                                verbose_name='4% от общей суммы в письменном виде',
                                                help_text='4% от общей суммы в письменном виде')
    loan_amount_text = models.CharField('Оплачиваемая сумма в письменном виде',
                                        max_length=255, null=True, blank=True)
    prilojenie_date = models.DateField('Дата приложения',
                                       null=True, blank=True)
    prilojenie_count = models.IntegerField('Количество месяцев', default=0,
                                           null=True, blank=True)
    prilojenie_count_text = models.CharField('Количество месяцев текст',
                                             max_length=255, null=True,
                                             blank=True,
                                             help_text='''Текст количество 
                                             месяцев (6 месяцев)''')
    anketa_date_register = models.DateField('Дата регистрации анкеты',
                                            null=True, blank=True)
    contract_date = models.DateField('Дата договора ссуды',

templates/users/operators_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Start breadcumb Area -->
<div class="page-area">
    <div class="breadcumb-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="breadcrumb">
                    <div class="bread-inner">
                        <div class="section-headline white-headline">
                            <h2>Список Операторов</h2>
                        </div>
                        <ul class="breadcrumb-bg">
                            <li class="home-bread"><a href="{% url 'home' %}">Главная</a></li>
                            <li><a href="{% url 'admin_page' %}">Панель управления</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcumb Area -->

<!-- Panel Filtering rows -->
<div class="panel p-tb-2">
    <div class="panel-body">
        <div class="btn-block" style="text-align: right; padding: 2vh 4vw;">
            <a href="{% url 'operator_signup' %}" class="btn btn-success"
                style="text-transform: uppercase; font-weight: bold">Регистрация Оператора</a>
        </div>
        <table class="center-align table table-bordered table-hover toggle-circle" id="exampleFootableFiltering"
            data-paging="true" data-filtering="true" data-sorting="true">


            <thead>
                <th class="center-align" data-name="id" data-type="number" data-breakpoints="xs" width="3%">№</th>
                <th data-name="login" class="center-align">Логин</th>
                <th data-name="login" class="center-align">Телефон</th>
                <th data-name="management" width="9%" class="center-align">Управление</th>
                </tr>
            </thead>
            <tbody>
                {% for x in object_list %}
                <tr>
                    <td class="counterCell center-align"></td>
                    <td class="center-align">{{ x.username.upper }}</td>
                    <td class="center-align">{{ x.user_phone_number1 }}</td>
                    <td class="center-align">
                        <a href="{% url 'user_detail' x.pk %}"
                            style="background:#03bfe2; color:#fff; font-weight:700; font-size:13px; padding:4px 10px; border-radius: 6px;"><i
                                class="fa fa-user"></i></a>
                        <a href="{% url 'user_update' x.pk %}"
                            style="background:green; color:#fff; font-weight:700; font-size:13px; padding:4px 10px; border-radius: 6px; margin-left:1px;"><i
                                class="fa fa-gears"></i></a>

                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <!-- Start Paginator -->
        <div class="col-md-12 col-sm-12 col-xs-12">
            {% if is_paginated %}
            <div class="blog-pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                    {% else %}
                    <li class="disabled"><span>Prev</span></li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span>
                    </li>
                    {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
                    {% else %}
                    <li class="disabled"><span>Next</span></li>
                    {% endif %}
                </ul>
            </div>
            {% endif %}
        </div>
        <!-- End Paginator -->
    </div>
</div>
<!-- End Panel Filtering -->


{% endblock %}

templates/users/user_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Start breadcumb Area -->
<div class="page-area">
    <div class="breadcumb-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="breadcrumb">
                    <div class="bread-inner">
                        <div class="section-headline white-headline">
                            <h2>удаление участника</h2>
                        </div>
                        <ul class="breadcrumb-bg">
                            <li class="home-bread">главная</li>
                            <li>Панель управления</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcumb Area -->

<div class="container p-tb-2">
    <form method="post" action="{% url 'delete' user.pk %}">
        {% csrf_token %}
        <h2>Вы действительно хотите удалить участника "{{ user }}" ?</h2>
        <button class="btn btn-danger" type="submit">Удалить</button>
    </form>
</div>

{% endblock %}

templates/users/user_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Start breadcumb Area -->
<div class="page-area">
    <div class="breadcumb-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="breadcrumb">
                    <div class="bread-inner">
                        <div class="section-headline white-headline">
                            <h3>Здравствуйте {{ object.user_full_name.capitalize }}</h3>
                        </div>
                        <ul class="breadcrumb-bg">
                            <li class="home-bread"><a href="{% url 'home' %}">Главная</a></li>
                            <li>Профиль</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcumb Area -->
<div class="container">
    <div class="row mar-row">
        <div class="header-of-table" style="padding: 15px">
            <a href="{% url 'password_change' %}" class="btn btn-info">Изменить пароль</a>

            {% if question and not_staff %}
                <a href="{% url 'quotes:vote' question %}" class="btn
                btn-info">Голосование</a>
            {% endif %}

            {% if user.is_superuser or user.user_is_operator %}
                <a href="{% url 'agreement_list' pk=object.pk %}" class="btn btn-info">Список договоров</a>
            {% endif %}
        </div>
        <div class="project-feature">
            <!-- Start column -->
            <div class="col-md-5 col-sm-6 col-xs-12">
                <div class="project-history">
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}><h4 style="color: #31b0d5">{{ message }}</h4></li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    <h4>Данные участника</h4>
                    <div class="project-name">
                        <table>
                            <tr>
                                <th>ФИО:</th>
                                <td>{{ object.user_full_name }}</td>
                            </tr>
                            {% if user.is_superuser %}
                            <tr>
                                <th>Баланс:</th>
                                <td>{{ object.user_balance }}</td>
                            </tr>
                            {% endif %}
                            <tr>
                                <th>Номер очереди:</th>
                                <td>{{ object.user_position }}</td>
                            </tr>
                            <tr>
                                <th>Регион:</th>
                                <td>{{ object.user_region }}</td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    {% if user.is_superuser %}
                                        <a href="{% url 'reset_user_password' pk=object.pk %}" class="btn btn-info">Сбросить пароль пользователя</a>
                                    {% endif %}
                                </td>
                            </tr>
                        </table>

                    </div>
                </div>
            </div>

            <!-- Start column -->
            <div class="col-md-7 col-sm-6 col-xs-12">
                <div class="row project-wrapper">
                    {% if notification %}
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="single-project-inner">
                            <div class="project-inner">
                                <div class="project-icon">
                                    <i class="fa fa-info-circle"></i>
                                </div>
                                <div class="project-text">
                                    <h4>Оповещение от Жилищного кооператива</h4>
                                    <p><h4 style="color: #31b0d5">{{ notification.description }}</h4></p>
                                    {% if notification.vote_file %}
                                    <h6>
                                        Прикрепленный докумен: <a href="{{notification.vote_file.url}}">Скачать</a>
                                    </h6>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="single-project-inner">
                            <div class="project-inner">
                                <div class="project-icon">
                                    <i class="fa fa-info-circle"></i>
                                </div>
                                <div class="project-text">
                                    <h4>Оповещение для {{object.username}}</h4>
                                    <p>{{ object.user_notifications }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="single-project-inner user-list">
                            <style>.single-project-inner.user-list {
                                height: 500px;
                                overflow: scroll;
                            }</style>
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th scope="col">Имя</th>
                                    <th scope="col">Позиция</th>
                                </tr>
                                </thead>

                                {% for user in users %}
                                <tr {% if user.id == object.id %}style="background: #1084b454;" {% endif %}>

                                    <td>{{ user }}</td>
                                    <td>{{ user.user_position }}</td>

                                </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End column -->
        </div>
    </div>
</div>
{% endblock %}

templates/users/user_update.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}
{% block content %}
<!-- Start breadcumb Area -->
<div class="page-area">
    <div class="breadcumb-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="breadcrumb">
                    <div class="bread-inner">
                        <div class="section-headline white-headline">
                            <h2>{{ object.user_full_name }}</h2>
                        </div>
                        <ul class="breadcrumb-bg">
                            <li class="home-bread"><a href="{% url 'home' %}">Главная</a></li>
                            <li><a href="{% url 'admin_page' %}">Панель управления</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcumb Area -->

<div class="container p-tb-2 user_change">
    <div class="col-md-12 col-sm-6 col-xs-12">
        <form method="post">
            {% csrf_token %}
            <div class="col-md-6">
                {{ form.username|as_crispy_field }}
                {{ form.user_full_name|as_crispy_field }}
                {{ form.user_full_name_plural|as_crispy_field }}
                {{ form.user_balance|as_crispy_field }}
                {{ form.user_passport_given_by|as_crispy_field }}

                <div id="div_id_user_passport_from_date" class="form-group">
                    <label for="id_user_passport_from_date" class="">
                        Выдан от
                    </label>
                    <div class="">
                        <input type="date" name="user_passport_from_date"
                            value="{{ object.user_passport_from_date|date:'Y-m-d' }}" class="dateinput form-control"
                            id="id_user_passport_from_date">
                    </div>
                </div>

                {{ form.user_inn|as_crispy_field }}
                {{ form.user_region|as_crispy_field }}
		
		{% if object.user_is_queued and user.is_superuser %}
                {{ form.user_is_queued|as_crispy_field }}
                {% else %}

                <div class="hidden">
                    {{ form.user_is_queued|as_crispy_field }}
                </div>
                {% endif %}


            </div>
            <div class="col-md-6">

                <div id="div_id_user_birthday" class="form-group">
                    <label for="id_user_birthday" class="">
                        День рождения
                    </label>
                    <div class="">
                        <input type="date" name="user_birthday" value="{{ object.user_birthday|date:'Y-m-d' }}"
                            class="dateinput form-control" id="id_user_birthday">
                    </div>
                </div>

                {{ form.user_birthday_city|as_crispy_field }}
                {{ form.user_passport_address|as_crispy_field }}
                {{ form.user_real_address|as_crispy_field }}
                {{ form.user_phone_number1|as_crispy_field }}
                {{ form.user_phone_number2|as_crispy_field }}
                {{ form.user_notifications|as_crispy_field }}

                <button type="submit" class="btn btn-info">Сохранить</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}